apiVersion: v1
kind: Service
metadata:
  name: opendj
spec:
  ports:
    - port: 389
      targetPort: 389
      protocol: "TCP"
      name: opendj-389
    - port: 636
      targetPort: 636
      protocol: "TCP"
      name: opendj-636
  selector:
    name: opendj