# We use a single OpenDJ instance as the config and CTS store for the cluster
# This instance is ephemeral - just for demo purposes
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opendj
spec:
  replicas: 1
  template:
    metadata:
      labels:
         name: opendj
    spec:
      containers:
      - name: opendj
        image: forgerock/opendj:latest
        #imagePullPolicy: Always
        ports:
        - containerPort: 389
          protocol: TCP
        - containerPort: 636
          protocol: TCP
        volumeMounts:
          - name: secrets
            mountPath: /var/secrets
#            readOnly: true
#          - name: opendj-disk
#            mountPath: /opt/opendj/data
      volumes:
        - name: secrets
          secret:
            secretName: fr-secrets
#        - name: opendj-disk
#          persistentVolumeClaim:
#            claimName: opendj-storage