# Secrets for OpenAM stack deployment. This will be mounted on all containers so they can get their
# passwords, etc.
# Note that secret vals are base 64 encoded
# base64 of 'password' is 'cGFzc3dvcmQ='
# Watch for trailing \n when you encode!
apiVersion: v1
kind: Secret
metadata:
  name: fr-secrets
type: Opaque
data:
  dirmanager.pw: cGFzc3dvcmQ=
  am.enc.key: TzZRV3dIUE80b3MrekV6M05xbi8yZGFBWVd5aUZFMzINCg==
  amadmin.pw: cGFzc3dvcmQ=
